on:
  push:
    branches: [main, master]
  schedule:
    - cron: '0 0 * * *'

name: Fluxo de Automatização

jobs:
  MeuRobo:
    runs-on: ubuntu-22.04

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v4

      - name: Instalar o Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.6.0

      - name: Instalar bibliotecas de Python
        run: poetry install --no-root

      - name: Instalar o Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.3.450

      - name: Renderizar relatório Quarto
        run: poetry run quarto render projeto1/projeto1.qmd

      - name: Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Atualização de relatório automatizada